NOTIFICATION_APP_NAME = "NOTIFICATION_APP_NAME"
NOTIFICATION_URGENCY_LEVEL = "NOTIFICATION_URGENCY_LEVEL"
NOTIFICATION_ICON = "NOTIFICATION_ICON"
NOTIFICATION_EXPIRE_TIME = "NOTIFICATION_EXPIRE_TIME"
WAIT_TIME = "WAIT_TIME"

SUPPORTED_FIELDS = [
    NOTIFICATION_APP_NAME, NOTIFICATION_URGENCY_LEVEL, NOTIFICATION_ICON, NOTIFICATION_EXPIRE_TIME,
    WAIT_TIME
]

REQUIRED_FIELDS = [
    NOTIFICATION_APP_NAME, WAIT_TIME
]
# /mnt/Development/Development/spanish/data/spanish.png
