# constant for notification configs
NOTIFICATION_APP_NAME = "APP_NAME"
NOTIFICATION_URGENCY_LEVEL = "URGENCY_LEVEL"
NOTIFICATION_ICON = "ICON"
NOTIFICATION_EXPIRE_TIME = "EXPIRE_TIME"

# constant for app configs
WAIT_TIME = "WAIT_TIME"

SUPPORTED_FIELDS_FOR_NOTIFICATION = [NOTIFICATION_APP_NAME, NOTIFICATION_URGENCY_LEVEL, NOTIFICATION_ICON,
                                     NOTIFICATION_EXPIRE_TIME]
REQUIRED_FIELDS_FOR_NOTIFICATION = [NOTIFICATION_APP_NAME]
SUPPORTED_FIELDS_FOR_APP = [WAIT_TIME]
REQUIRED_FIELDS_FOR_APP = [WAIT_TIME]
